### ISSUE TITLE
Incorrect term on line 83

### ISSUE THREAD

**Issue by dpkay** [Trodek/Bezier-Easing#1]
I pulled your source for an experiment and found that you accidentally multiply VecCCoord(p1_coord) with time in line 83... you probably want to remove the "*time* factor in the last summand.

https://github.com/Trodek/Bezier-Easing/blob/6905e973964682f04171ee7204be8591d880cbb2/BezierEasing/BezierEasing.cpp#L83

Thanks for sharing this code!

**Comment by Trodek** [comment]
I'm sorry it took so long. I fixed the issue, thanks!
